### ISSUE TITLE
Fruit Ninja v1.0

### ISSUE THREAD

**Issue by p0008874** [hikari-no-yume/touchHLE#11]
```
touchHLE v0.1.0 — https://touchhle.org/

touchHLE: Warning: app binary depends on unexpected dylib "/usr/lib/libsqlite3.0.dylib"
touchHLE: Warning: app binary depends on unexpected dylib "/usr/lib/libz.1.dylib"
Address of start function: GuestFunction(0x8428)
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13ae2c in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13aea0 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13aeec in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13af04 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13af50 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13afb8 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13affc in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13b034 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13b054 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13b0a4 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13b0c4 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13b0e0 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13b1c8 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13b224 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13b280 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13b2dc in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13b334 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13b34c in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13b5f8 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13b6e8 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13b710 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13b748 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13ba84 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13bb38 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13bc48 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13bc8c in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13bf8c in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13c4e8 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" at 0x13c528 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13ae50 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13ae78 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13afac in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13aff0 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b028 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b048 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b098 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b0f4 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b100 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b14c in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b198 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b1bc in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b1f4 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b218 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b250 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b274 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b2ac in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b2d0 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b308 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b328 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b374 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b380 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b38c in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b398 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b3a4 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b3b0 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b3bc in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b618 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b624 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b698 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b73c in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b798 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b7a4 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b7d4 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b814 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b820 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b894 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b8c4 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b914 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b920 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b9a8 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13b9f0 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13ba38 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bab4 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bad0 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bb2c in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bb70 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bb7c in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bbb8 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bc3c in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bc80 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bc94 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bd00 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bd84 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bd90 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bdd0 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13be0c in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13be70 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13be7c in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bed8 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bef8 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bf18 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bf38 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bfa8 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13bfb4 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c048 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c0c0 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c154 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c160 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c1d8 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c1fc in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c220 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c2b4 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c2c0 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c2cc in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c320 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c350 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c3c4 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c438 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c460 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c51c in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c558 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c578 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c598 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c5a4 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13c9c0 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13ca14 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" at 0x13ca20 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv121__vmi_class_type_infoE" at 0x13bf44 in "Fruit"
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv121__vmi_class_type_infoE" at 0x13c488 in "Fruit"
thread 'main' panicked at 'assertion failed: flags == 0x7C8', src\frameworks\foundation\ns_string.rs:586:5
stack backtrace:
   0:     0x7ff6df9bf362 - <unknown>
   1:     0x7ff6df9d771b - <unknown>
   2:     0x7ff6df9bb5ca - <unknown>
   3:     0x7ff6df9bf0ab - <unknown>
   4:     0x7ff6df9c1899 - <unknown>
   5:     0x7ff6df9c151a - <unknown>
   6:     0x7ff6df9c2121 - <unknown>
   7:     0x7ff6df9c1e6a - <unknown>
   8:     0x7ff6df9bfd8f - <unknown>
   9:     0x7ff6df9c1b70 - <unknown>
  10:     0x7ff6dfe63fd5 - <unknown>
  11:     0x7ff6dfe640cc - <unknown>
  12:     0x7ff6df942437 - <unknown>
  13:     0x7ff6df8f86f0 - <unknown>
  14:     0x7ff6df8fb560 - <unknown>
  15:     0x7ff6df9592aa - <unknown>
  16:     0x7ff6df95f944 - <unknown>
  17:     0x7ff6df9b5cfe - <unknown>
  18:     0x7ff6df90022c - <unknown>
  19:     0x7ff6dfe594bc - <unknown>
  20:     0x7ffbd7897614 - BaseThreadInitThunk
  21:     0x7ffbd85626a1 - RtlUserThreadStart
```
ipa used:[Fruit_Ninja_v1.0_os221.ipa](https://archive.org/download/ios_2_ipa/Fruit_Ninja_v1.0_os221.ipa)
The error will be dupe from #9

**Comment by hikari-no-yume** [comment]
Hi. Since there's almost an infinitely long list of incompatible apps right now, I don't think it's a good time to create issues tracking incompatible apps.

**Comment by upintheairsheep** [comment]
Also, tried the infamous I am Rich app to get this: 
touchHLE v0.1.0 — https://touchhle.org/

Address of start function: GuestFunction(0x2000)
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_cache" at 0x41fc in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_cache" at 0x4238 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_cache" at 0x4314 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_cache" at 0x4350 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_cache" at 0x43b8 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_cache" at 0x43f4 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_cache" at 0x445c in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_cache" at 0x4498 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_cache" at 0x451c in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_cache" at 0x4558 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_cache" at 0x46c4 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_cache" at 0x4700 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_vtable" at 0x4200 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_vtable" at 0x423c in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_vtable" at 0x4318 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_vtable" at 0x4354 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_vtable" at 0x43bc in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_vtable" at 0x43f8 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_vtable" at 0x4460 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_vtable" at 0x449c in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_vtable" at 0x4520 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_vtable" at 0x455c in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_vtable" at 0x46c8 in "IAmRich"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_vtable" at 0x4704 in "IAmRich"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_exit" at 0x4004 in "IAmRich"
CPU emulation begins now.
touchHLE::frameworks::uikit::ui_nib: TODO: UIProxyObject replacement for IBFirstResponder, instance 0x30009ef0 left unreplaced
thread 'main' panicked at 'Class "UIViewController" (0x30009d30) is unimplemented. Call to class method "alloc".', src\objc\messages.rs:102:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Register state immediately after panic:
         R0: 0x00004514  R1: 0x00002928  R2: 0x3000a060  R3: 0x00000000
         R4: 0x00000001  R5: 0x30009dd0  R6: 0xffffff48  R7: 0xffffff38
         R8: 0x00000000  R9: 0x00000000 R10: 0x00000000 R11: 0x00000000
        R12: 0x0000206d  SP: 0xffffff2c  LR: 0x00002097  PC: 0x000028ec
Attempting to produce stack trace for main thread:
 0. 0x28ec (PC)
 1. 0x2097 (LR)
 2. 0x2034
Next FP (0x0) is outside the stack.

**Comment by hikari-no-yume** [comment]
Yeah, UIViewController is missing, I'm sure a lot of apps will hit that. But that's a completely different issue, why is it mentioned here?

**Comment by hikari-no-yume** [comment]
Oops, didn't notice there was a pirate link in this issue until now, I'm going to have to delete it. Sorry.
