### ISSUE TITLE
Mystery Mania crashes on exit

### ISSUE THREAD

**Issue by hikari-no-yume** [hikari-no-yume/touchHLE#142]
Probably a retain/release bug:

<details>
<summary>

`thread 'main' panicked at 'Can't free 0x380049e0, unknown allocation!', src/mem/allocator.rs:206:13`

</summary>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: touchHLE::mem::allocator::Allocator::free
             at ./src/mem/allocator.rs:206:13
   3: touchHLE::mem::Mem::free
             at ./src/mem.rs:460:20
   4: touchHLE::libc::stdlib::free
             at ./src/libc/stdlib.rs:44:5
   5: <fn(&mut touchHLE::environment::Environment,P0) .> R as touchHLE::abi::CallFromGuest>::call_from_guest
             at ./src/abi.rs:188:30
   6: touchHLE::environment::Environment::handle_cpu_state
             at ./src/environment.rs:756:29
   7: touchHLE::environment::Environment::run_inner
             at ./src/environment.rs:807:23
   8: touchHLE::environment::Environment::run_call
             at ./src/environment.rs:624:9
   9: touchHLE::abi::GuestFunction::call_without_pushing_stack_frame
             at ./src/abi.rs:134:9
  10: touchHLE::objc::messages::objc_msgSend_inner
             at ./src/objc/messages.rs:93:46
  11: touchHLE::objc::messages::objc_msgSend
             at ./src/objc/messages.rs:137:5
  12: <fn(&mut touchHLE::environment::Environment,P0,P1) .> R as touchHLE::abi::CallFromGuest>::call_from_guest
             at ./src/abi.rs:188:30
  13: touchHLE::environment::Environment::handle_cpu_state
             at ./src/environment.rs:756:29
  14: touchHLE::environment::Environment::run_inner
             at ./src/environment.rs:807:23
  15: touchHLE::environment::Environment::run_call
             at ./src/environment.rs:624:9
  16: touchHLE::abi::GuestFunction::call_without_pushing_stack_frame
             at ./src/abi.rs:134:9
  17: touchHLE::objc::messages::objc_msgSend_inner
             at ./src/objc/messages.rs:93:46
  18: touchHLE::objc::messages::objc_msgSend
             at ./src/objc/messages.rs:137:5
  19: <fn(&mut touchHLE::environment::Environment,P0,P1) .> R as touchHLE::abi::CallFromGuest>::call_from_guest
             at ./src/abi.rs:188:30
  20: touchHLE::environment::Environment::handle_cpu_state
             at ./src/environment.rs:756:29
  21: touchHLE::environment::Environment::run_inner
             at ./src/environment.rs:807:23
  22: touchHLE::environment::Environment::run_call
             at ./src/environment.rs:624:9
  23: touchHLE::abi::GuestFunction::call_without_pushing_stack_frame
             at ./src/abi.rs:134:9
  24: touchHLE::objc::messages::objc_msgSend_inner
             at ./src/objc/messages.rs:93:46
  25: touchHLE::objc::messages::objc_msgSend
             at ./src/objc/messages.rs:137:5
  26: <fn(&mut touchHLE::environment::Environment,P0,P1) .> R as touchHLE::abi::CallFromGuest>::call_from_guest
             at ./src/abi.rs:188:30
  27: <T as touchHLE::abi::CallFromHost<R,(P0,P1,P2)>>::call_from_host
             at ./src/abi.rs:269:17
  28: touchHLE::objc::messages::msg_send
             at ./src/objc/messages.rs:209:9
  29: touchHLE::frameworks::uikit::ui_application::exit
             at ./src/frameworks/uikit/ui_application.rs:261:18
  30: touchHLE::frameworks::uikit::handle_events
             at ./src/frameworks/uikit.rs:61:17
  31: touchHLE::frameworks::foundation::ns_run_loop::run_run_loop
             at ./src/frameworks/foundation/ns_run_loop.rs:189:24
  32: touchHLE::frameworks::foundation::ns_run_loop::CLASSES::{{closure}}
             at ./src/frameworks/foundation/ns_run_loop.rs:107:5
  33: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
  34: <fn(&mut touchHLE::environment::Environment,P0,P1) .> R as touchHLE::abi::CallFromGuest>::call_from_guest
             at ./src/abi.rs:188:30
  35: touchHLE::objc::messages::objc_msgSend_inner
             at ./src/objc/messages.rs:90:44
  36: touchHLE::objc::messages::objc_msgSend
             at ./src/objc/messages.rs:137:5
  37: <fn(&mut touchHLE::environment::Environment,P0,P1) .> R as touchHLE::abi::CallFromGuest>::call_from_guest
             at ./src/abi.rs:188:30
  38: <T as touchHLE::abi::CallFromHost<R,(P0,P1)>>::call_from_host
             at ./src/abi.rs:269:17
  39: touchHLE::objc::messages::msg_send
             at ./src/objc/messages.rs:209:9
  40: touchHLE::frameworks::uikit::ui_application::UIApplicationMain
             at ./src/frameworks/uikit/ui_application.rs:233:17
  41: <fn(&mut touchHLE::environment::Environment,P0,P1,P2,P3) .> R as touchHLE::abi::CallFromGuest>::call_from_guest
             at ./src/abi.rs:188:30
  42: touchHLE::environment::Environment::handle_cpu_state
             at ./src/environment.rs:756:29
  43: touchHLE::environment::Environment::run_inner
             at ./src/environment.rs:807:23
  44: touchHLE::environment::Environment::run::{{closure}}
             at ./src/environment.rs:606:76
  45: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
  46: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panic/unwind_safe.rs:271:9
  47: std::panicking::try::do_call
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
  48: ___rust_try
  49: std::panicking::try
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
  50: std::panic::catch_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
  51: touchHLE::environment::Environment::run
             at ./src/environment.rs:606:19
  52: touchHLE::main
             at ./src/lib.rs:283:5
  53: touchHLE::main
             at ./src/bin.rs:11:5
  54: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Register state immediately after panic:
	 R0: 0x380049e0	 R1: 0x3061a4d0	 R2: 0x00000000	 R3: 0x00000024
	 R4: 0x00000020	 R5: 0x000492a8	 R6: 0x000492a8	 R7: 0xfffffea8
	 R8: 0x00000001	 R9: 0x00000000	R10: 0x00000000	R11: 0x00000000
	R12: 0x00047178	 SP: 0xfffffea8	 LR: 0x300718a8	 PC: 0x30075e44
Attempting to produce stack trace for main thread:
 0. 0x30075e44 (PC)
 1. 0x300718a8 (LR)
 2. 0x1ac8d
 3. 0x1acc5
 4. 0x40a5
 5. 0x4149
 6. 0x1b967
 7. [host function]
 8. [host function]
 9. [host function]
10. 0x2a48
Next FP (0x0) is outside the stack.
```
</details>

**Comment by ciciplusplus** [comment]
@hikari-no-yume shouldn't we close this one since merge of https://github.com/hikari-no-yume/touchHLE/commit/80a1d528af7ec683043a448def018f3d7592f25e ?

**Comment by hikari-no-yume** [comment]
Depends if the issue has actually been fixed by that or if it still crashes for some other reason?

**Comment by ciciplusplus** [comment]
Same issue is logged on exit, but it's not crashing anymore:

```
MysteryMania[0] About to Allocate Buffer 3
MysteryMania[0] About to Start Audio Queue
User requested quit, exiting.
touchHLE::mem::allocator: Can't free 0x375912e0, unknown allocation!
touchHLE::objc::objects: Warning: 0x374f7ae0 was deallocated with non-zero reference count: 1

Process finished with exit code 0
```
