### ISSUE TITLE
BookWorm (version 2.x) loading screen and crashes after a bit

### ISSUE THREAD

**Issue by GreenNinja2525** [hikari-no-yume/touchHLE#150]
`[Please delete this Issue, it won't let me]` `[Comment Removed]`

**Comment by klaxons1** [comment]
I can't see Bookworm in the list of supported apps. Do you?

**Comment by GreenNinja2525** [comment]
`[Please delete this Issue, it won't let me]` `[Comment Removed]`

**Comment by nighto** [comment]
I tried reproducing the bug here and it crashes as soon as it tries to run, meaning it doesn't go pass the initial splash screen.

For the reference, here's the output of `RUST_BACKTRACE=1 cargo run`:

```
Picked: touchHLE_apps\Bookworm 1.0.2.ipa
App bundle info:
- Display name: Bookworm
- Version: 37
- Identifier: com.popcap.Bookworm
- Internal name (canonical): Bookworm.app
- Minimum OS version: 2.2.1

No options found for this app in touchHLE_default_options.txt
No options found for this app in touchHLE_options.txt

touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Failed: Could not initialize OpenGL / GLES library.
touchHLE::gles: Trying: OpenGL ES 1.1 via touchHLE GLES1-on-GL2 layer
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL 4.6.0 - Build 31.0.101.2115 / Intel / Intel(R) UHD Graphics
touchHLE::dyld: Warning: unhandled external relocation "___cxa_pure_virtual" in "Bookworm" at 0x1883f8, 0x188404, 0x188408, 0x1888e0, 0x1888f4, 0x188934, 0x188974, 0x1891a4, 0x1891b8, 0x189b98, 0x189b9c, 0x189ba0, 0x18a2a4, 0x18a2b8, 0x18a2f8, 0x18a338, 0x18ac24, 0x18ac38, 0x18ac78, 0x18d2cc, 0x18d2e0, 0x18d320, 0x18d518, 0x18d52c, 0x18d844, 0x18d8a8, 0x18dc78, 0x18ecc8, 0x18eccc, 0x18ecd0, 0x18ecd4, 0x18ecd8, 0x18ecdc, 0x18ece0, 0x18ece4, 0x18ece8, 0x18ecec, 0x18ecf0, 0x18edec, 0x18edf0, 0x18edf4, 0x18edf8, 0x18edfc, 0x18ee00, 0x18ee04, 0x18ee08, 0x18ee0c, 0x18ee10, 0x18ee14, 0x18ee18, 0x18ee1c, 0x18ee20, 0x18ee24, 0x18ee28, 0x18ee2c, 0x18f52c, 0x18f530, 0x18f534, 0x18f538
touchHLE::dyld: Warning: unhandled external relocation "__ZTISt9exception" in "Bookworm" at 0x188e60
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv117__class_type_infoE" in "Bookworm" at 0x187834, 0x18783c, 0x187844, 0x187a64, 0x187a6c, 0x187f30, 0x187f4c, 0x187f54, 0x187f74, 0x1883e0, 0x1883e8, 0x1888c8, 0x1889b4, 0x188b90, 0x188b98, 0x188fd0, 0x188fe8, 0x18918c, 0x189b6c, 0x18a28c, 0x18ac0c, 0x18d2b4, 0x18d500, 0x18d56c, 0x18d808, 0x18dbb8, 0x18dc38, 0x18dca4, 0x18dcac, 0x18dcd0, 0x18ddbc, 0x18de38, 0x18de74, 0x18df10, 0x18e368, 0x18e7bc, 0x18ecb0, 0x18edd4
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv120__si_class_type_infoE" in "Bookworm" at 0x187aa8, 0x187bfc, 0x187f5c, 0x187f68, 0x188020, 0x18840c, 0x18855c, 0x188720, 0x1888b0, 0x1888bc, 0x18890c, 0x188918, 0x18894c, 0x188958, 0x1889a8, 0x188bb8, 0x188d08, 0x188e58, 0x188e64, 0x189000, 0x189174, 0x189180, 0x1891ec, 0x1893c0, 0x1896f4, 0x189860, 0x1899e8, 0x189ba4, 0x189ed0, 0x18a090, 0x18a274, 0x18a280, 0x18a2d0, 0x18a2dc, 0x18a310, 0x18a31c, 0x18a36c, 0x18a378, 0x18a4d4, 0x18a624, 0x18a774, 0x18a8fc, 0x18aa4c, 0x18abf4, 0x18ac00, 0x18ac50, 0x18ac5c, 0x18acac, 0x18ae50, 0x18b1a0, 0x18d130, 0x18d29c, 0x18d2a8, 0x18d2f8, 0x18d304, 0x18d354, 0x18d360, 0x18d4e8, 0x18d4f4, 0x18d560, 0x18d584, 0x18d6e0, 0x18d760, 0x18d7a8, 0x18d810, 0x18d81c, 0x18d828, 0x18da5c, 0x18dcc4, 0x18dcd8, 0x18dda0, 0x18de50, 0x18de5c, 0x18de68, 0x18e0b4, 0x18e0c0, 0x18e218, 0x18e408, 0x18e4ac, 0x18e664, 0x18e9c8, 0x18eb18, 0x18ec68, 0x18ecf4, 0x18ed74
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_vtable" in "Bookworm" at 0x1924d8, 0x192514, 0x192798, 0x1927d4, 0x192a50, 0x192a8c, 0x192b54, 0x192b90, 0x192c8c, 0x192cc8, 0x192e30, 0x192e6c, 0x19303c, 0x193078
touchHLE::dyld: Warning: unhandled external relocation "__ZTVN10__cxxabiv121__vmi_class_type_infoE" in "Bookworm" at 0x18784c, 0x187d4c, 0x1881e0, 0x1889cc, 0x1891f8, 0x18952c, 0x189cf4, 0x18acb8, 0x18afd8, 0x18d8b0, 0x18dc7c, 0x18df40, 0x18e4f0
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_cache" in "Bookworm" at 0x1924d4, 0x192510, 0x192794, 0x1927d0, 0x192a4c, 0x192a88, 0x192b50, 0x192b8c, 0x192c88, 0x192cc4, 0x192e2c, 0x192e68, 0x193038, 0x193074
touchHLE::dyld: Warning: unhandled external relocation "__ZTIPc" in "Bookworm" at 0x1901d0
touchHLE::dyld: Warning: unhandled external relocation "__ZNKSt9exception4whatEv" in "Bookworm" at 0x18df3c
touchHLE::dyld: Warning: unhandled non-lazy symbol "_exit" at 0x1867bc in "Bookworm"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_UIKeyboardBoundsUserInfoKey" at 0x186e90 in "Bookworm"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_UIKeyboardDidShowNotification" at 0x186e94 in "Bookworm"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_UIKeyboardWillShowNotification" at 0x186e98 in "Bookworm"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_UIKeyboardDidHideNotification" at 0x186e9c in "Bookworm"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_UIKeyboardWillHideNotification" at 0x186ea4 in "Bookworm"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_UIDeviceOrientationDidChangeNotification" at 0x186ea8 in "Bookworm"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_kCFPreferencesCurrentApplication" at 0x187390 in "Bookworm"
touchHLE::dyld: Warning: unhandled non-lazy symbol "___mb_cur_max" at 0x3800c8e0 in "libstdc++.6.dylib"
CPU emulation begins now.
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x3000ca90), 0xfffffe6c, 0xfffffe6c) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_finalize(0xfffffe6c) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_finalize(0xfffffe6c) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x3000cf44), 0x3000bc10, 0x3000c000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x3000cf44), 0x3000bc20, 0x3000c000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x133519), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x13352d), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x1335e5), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x1336d8), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x1336f4), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x133710), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x13372c), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x133764), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x133780), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x13379c), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x133748), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x1337d4), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x1337b8), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x1337fc), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x133818), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x133904), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x133920), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x13393c), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x133958), 0x0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x133974), 0x0, 0x1000) (unimplemented)
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Failed: Could not initialize OpenGL / GLES library.
touchHLE::gles: Trying: OpenGL ES 1.1 via touchHLE GLES1-on-GL2 layer
touchHLE::gles: => Success!
touchHLE::frameworks::opengles::eagl: Driver info: OpenGL 4.6.0 - Build 31.0.101.2115 / Intel / Intel(R) UHD Graphics
thread 'main' panicked at 'Object 0x3000bf30 (class "UIApplication", 0x3000ac80) does not respond to selector "statusBarOrientation"!', src\objc\messages.rs:60:13
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src\panicking.rs:67
   2: touchHLE::objc::messages::objc_msgSend_inner
             at .\src\objc\messages.rs:60
   3: touchHLE::objc::messages::objc_msgSend
             at .\src\objc\messages.rs:163
   4: touchHLE::abi::impl$26::call_from_guest<tuple$<>,touchHLE::mem::Ptr<touchHLE::objc::objects::objc_object,true>,touchHLE::objc::selectors::SEL>
             at .\src\abi.rs:188
   5: touchHLE::environment::Environment::handle_cpu_state
             at .\src\environment.rs:756
   6: touchHLE::environment::Environment::run_inner
             at .\src\environment.rs:807
   7: touchHLE::environment::Environment::run_call
             at .\src\environment.rs:624
   8: touchHLE::abi::GuestFunction::call_without_pushing_stack_frame
             at .\src\abi.rs:134
   9: touchHLE::objc::messages::objc_msgSend_inner
             at .\src\objc\messages.rs:119
  10: touchHLE::objc::messages::objc_msgSend
             at .\src\objc\messages.rs:163
  11: touchHLE::abi::impl$26::call_from_guest<tuple$<>,touchHLE::mem::Ptr<touchHLE::objc::objects::objc_object,true>,touchHLE::objc::selectors::SEL>
             at .\src\abi.rs:188
  12: touchHLE::abi::impl$48::call_from_host<void (*)(ref_mut$<touchHLE::environment::Environment>,touchHLE::mem::Ptr<touchHLE::objc::objects::objc_object,true>,touchHLE::objc::selectors::SEL),tuple$<>,touchHLE::mem::Ptr<touchHLE::objc::objects::objc_object,tru
             at .\src\abi.rs:269
  13: touchHLE::objc::messages::msg_send<tuple$<>,tuple$<touchHLE::mem::Ptr<touchHLE::objc::objects::objc_object,true>,touchHLE::objc::selectors::SEL,touchHLE::mem::Ptr<touchHLE::objc::objects::objc_object,true> > >
             at .\src\objc\messages.rs:254
  14: touchHLE::frameworks::uikit::ui_application::UIApplicationMain
             at .\src\frameworks\uikit\ui_application.rs:201
  15: touchHLE::abi::impl$30::call_from_guest<tuple$<>,i32,touchHLE::mem::Ptr<touchHLE::mem::Ptr<u8,true>,true>,touchHLE::mem::Ptr<touchHLE::objc::objects::objc_object,true>,touchHLE::mem::Ptr<touchHLE::objc::objects::objc_object,true> >
             at .\src\abi.rs:188
  16: touchHLE::environment::Environment::handle_cpu_state
             at .\src\environment.rs:756
  17: touchHLE::environment::Environment::run_inner
             at .\src\environment.rs:807
  18: touchHLE::environment::impl$1::run::closure$0
             at .\src\environment.rs:606
  19: core::ops::function::FnOnce::call_once<touchHLE::environment::impl$1::run::closure_env$0,tuple$<> >
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\ops\function.rs:250
  20: core::panic::unwind_safe::impl$23::call_once<tuple$<>,touchHLE::environment::impl$1::run::closure_env$0>
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\panic\unwind_safe.rs:271
  21: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<touchHLE::environment::impl$1::run::closure_env$0>,tuple$<> >
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panicking.rs:500
  22: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<touchHLE::environment::impl$1::run::closure_env$0>,tuple$<> >
  23: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<touchHLE::environment::impl$1::run::closure_env$0> >
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panicking.rs:464
  24: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<touchHLE::environment::impl$1::run::closure_env$0>,tuple$<> >
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panic.rs:142
  25: touchHLE::environment::Environment::run
             at .\src\environment.rs:606
  26: touchHLE::main<std::env::Args>
             at .\src\lib.rs:286
  27: touchHLE::main
             at .\src\bin.rs:11
  28: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,alloc::string::String> > (*)(),tuple$<> >
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Register state immediately after panic:
         R0: 0x3000bf30  R1: 0x00136e14  R2: 0x00000000  R3: 0x00000008
         R4: 0x00191fa0  R5: 0xfffffecc  R6: 0x001935f8  R7: 0xffffff14
         R8: 0x3000bf40  R9: 0x00000000 R10: 0x3000bf30 R11: 0x001935fc
        R12: 0xfffffd60  SP: 0xfffffe68  LR: 0x0004a520  PC: 0x00134810
Attempting to produce stack trace for main thread:
 0. 0x134810 (PC)
 1. 0x4a520 (LR)
 2. [host function]
 3. 0x9164
Next FP (0x0) is outside the stack.
error: process didn't exit successfully: `target\debug\touchHLE.exe` (exit code: 101)
```
