### ISSUE TITLE
Any plans for Resident Evil Degeneration game?

### ISSUE THREAD

**Issue by pmsobrado** [hikari-no-yume/touchHLE#172]
I don't know what min iOS version this game needs, but I would love for touchHLE to have support for it!

Thanks!

**Comment by hikari-no-yume** [comment]
please read the text in the new issue box before submitting a new issue. it's there for a reason. i'm literally begging you

**Comment by hikari-no-yume** [comment]
(sorry, i'm just getting inundated with issues like this. regarding that Resident Evil game, it's pretty old, i imagine it'll work in touchHLE eventually.)

**Comment by pmsobrado** [comment]
Sorry, I found no other way to ask. I'll be patient then and see what happens in the future. Thanks.

**Comment by nighto** [comment]
I was curious to see what would be the minimal version and what are the logs, so here's the output for `RUST_BACKTRACE=1 cargo run` on that ipa:

```
Picked: touchHLE_apps\ResidentEvilDegeneration.ipa
App bundle info:
- Display name: resident evil DEGENERATION
- Version: 1.03.00
- Identifier: jp.co.capcom.residentevil.en
- Internal name (canonical): residentevil.app
- Minimum OS version: 2.2.1

No options found for this app in touchHLE_default_options.txt
No options found for this app in touchHLE_options.txt

touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Failed: Could not initialize OpenGL / GLES library.
touchHLE::gles: Trying: OpenGL ES 1.1 via touchHLE GLES1-on-GL2 layer
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL 4.6.0 - Build 31.0.101.2115 / Intel / Intel(R) UHD Graphics
touchHLE::environment: Warning: app binary depends on unexpected dylib "/usr/lib/libz.1.dylib"
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_cache" in "residentevil" at 0x233880, 0x2338bc, 0x233bb4, 0x233bf0, 0x233efc, 0x233f38, 0x234308, 0x234344, 0x6f8f70, 0x6f8fac
touchHLE::dyld: Warning: unhandled external relocation "__objc_empty_vtable" in "residentevil" at 0x233884, 0x2338c0, 0x233bb8, 0x233bf4, 0x233f00, 0x233f3c, 0x23430c, 0x234348, 0x6f8f74, 0x6f8fb0
touchHLE::dyld: Warning: unhandled non-lazy symbol "_exit" at 0x233004 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_mutexattr_destroy" at 0x233074 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_mutex_destroy" at 0x233078 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_create" at 0x23307c in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_detach" at 0x233080 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_mutex_trylock" at 0x233084 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_attr_init" at 0x233088 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_getschedparam" at 0x23308c in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_once" at 0x233090 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_cond_init" at 0x233094 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_mutex_lock" at 0x233098 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_cond_timedwait" at 0x23309c in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_exit" at 0x2330a0 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_join" at 0x2330a4 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_key_delete" at 0x2330a8 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_cond_wait" at 0x2330ac in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_mutex_unlock" at 0x2330b0 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_sigmask" at 0x2330b4 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_attr_setscope" at 0x2330b8 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_cond_destroy" at 0x2330bc in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_mutexattr_init" at 0x2330c0 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_cond_signal" at 0x2330c4 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_kill" at 0x2330c8 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_setspecific" at 0x2330cc in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_self" at 0x2330d0 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_attr_setdetachstate" at 0x2330d4 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_cond_broadcast" at 0x2330d8 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_key_create" at 0x2330dc in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_attr_destroy" at 0x2330e0 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_equal" at 0x2330e4 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_mutexattr_settype" at 0x2330e8 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_attr_getdetachstate" at 0x2330ec in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_getspecific" at 0x2330f0 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_mutex_init" at 0x2330f4 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_pthread_mutexattr_gettype" at 0x2330f8 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_glGenFramebuffersOES" at 0x2331cc in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_glFramebufferRenderbufferOES" at 0x2331d0 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_glIsRenderbufferOES" at 0x2331d4 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_glBindRenderbufferOES" at 0x2331d8 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_glIsFramebufferOES" at 0x2331dc in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_glDeleteFramebuffersOES" at 0x2331e0 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_glGenRenderbuffersOES" at 0x2331e4 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_glCheckFramebufferStatusOES" at 0x2331e8 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_glGetFramebufferAttachmentParameterivOES" at 0x2331ec in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_glGenerateMipmapOES" at 0x2331f0 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_glRenderbufferStorageOES" at 0x2331f4 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_glBindFramebufferOES" at 0x2331f8 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_glGetRenderbufferParameterivOES" at 0x2331fc in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_glFramebufferTexture2DOES" at 0x233200 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_glDeleteRenderbuffersOES" at 0x233204 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_kCLErrorDomain" at 0x23320c in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_kCLLocationAccuracyBest" at 0x233210 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_kCLDistanceFilterNone" at 0x233214 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "_mach_task_self_" at 0x233228 in "residentevil"
touchHLE::dyld: Warning: unhandled non-lazy symbol "___mb_cur_max" at 0x3800c8e0 in "libstdc++.6.dylib"
CPU emulation begins now.
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x3000ca90), 0xfffffe5c, 0xfffffe5c) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_finalize(0xfffffe5c) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_finalize(0xfffffe5c) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x3000cf44), 0x3000be90, 0x3000c000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x3000cf44), 0x3000bea0, 0x3000c000) (unimplemented)
Airplay v3.7.0beta [188763u]: main thread r9 = 0x0
thread 'main' panicked at 'Call to unimplemented function _pthread_cond_init', src\dyld.rs:509:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src\panicking.rs:67
   2: touchHLE::dyld::Dyld::do_lazy_link
             at .\src\dyld.rs:509
   3: touchHLE::dyld::Dyld::get_svc_handler
             at .\src\dyld.rs:405
   4: touchHLE::environment::Environment::handle_cpu_state
             at .\src\environment.rs:746
   5: touchHLE::environment::Environment::run_inner
             at .\src\environment.rs:807
   6: touchHLE::environment::impl$1::run::closure$0
             at .\src\environment.rs:606
   7: core::ops::function::FnOnce::call_once<touchHLE::environment::impl$1::run::closure_env$0,tuple$<> >
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\ops\function.rs:250
   8: core::panic::unwind_safe::impl$23::call_once<tuple$<>,touchHLE::environment::impl$1::run::closure_env$0>
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\panic\unwind_safe.rs:271
   9: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<touchHLE::environment::impl$1::run::closure_env$0>,tuple$<> >
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panicking.rs:500
  10: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<touchHLE::environment::impl$1::run::closure_env$0>,tuple$<> >
  11: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<touchHLE::environment::impl$1::run::closure_env$0> >
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panicking.rs:464
  12: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<touchHLE::environment::impl$1::run::closure_env$0>,tuple$<> >
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panic.rs:142
  13: touchHLE::environment::Environment::run
             at .\src\environment.rs:606
  14: touchHLE::main<std::env::Args>
             at .\src\lib.rs:286
  15: touchHLE::main
             at .\src\bin.rs:11
  16: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,alloc::string::String> > (*)(),tuple$<> >
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Register state immediately after panic:
         R0: 0x006fed04  R1: 0x00000000  R2: 0x00000000  R3: 0x006ff0e8
         R4: 0x006ff0b8  R5: 0x00000000  R6: 0x00000001  R7: 0xffffff18
         R8: 0xffffff28  R9: 0x00000000 R10: 0x3000beb0 R11: 0x00000000
        R12: 0x00031410  SP: 0xfffffef8  LR: 0x000314a8  PC: 0x0022b808
Attempting to produce stack trace for main thread:
 0. 0x22b808 (PC)
 1. 0x314a8 (LR)
 2. 0x2034
Next FP (0x0) is outside the stack.
error: process didn't exit successfully: `target\debug\touchHLE.exe` (exit code: 101)
```

**Comment by pmsobrado** [comment]
So the problem may be an unimplemented function?

**Comment by hikari-no-yume** [comment]
Yes, but that's just the first issue. Typically there are a large number of different issues which prevent any particular game from running.

**Comment by nighto** [comment]
Yes @pmsobrado, just to be clear, the emulator is in its infancy so that's why it only runs a handful of games: every function that a given app tries to access needs to be reimplemented. That is done by developers on a case by case: when they want to focus on running a certain app, they would implement every function that app needs. This could coincidently help other games to run as well, but of course it is not certain. The logs tells the first function it could not find but potentially (most like, certainly) there are others as well.

**Comment by pmsobrado** [comment]
I see, thanks for the responses!
