### ISSUE TITLE
Crash issues when launching app, cannot find unimplemented function

### ISSUE THREAD

**Issue by rachelombok** [hikari-no-yume/touchHLE#349]
### Describe the feature or issue.

Having issues launching an app using touchHLE GUI app picker. When I run the executable file and click on the app in the GUI, it can successfully identify my app and I get this in my terminal;
```
...
touchHLE::window: Driver info: OpenGL 2.1 ATI-5.5.17 / ATI Technologies Inc. / AMD Radeon Pro 5300M OpenGL Engine
Picked: touchHLE_apps/CoD.app
App bundle info:
- Display name: Cause of Death
- Version: 1.3.4
- Identifier: com.ea.causeofdeath.bv
- Internal name (canonical): CoD.app
- Minimum OS version: 3.0
...
```
and then at the bottom;
```
...
CPU emulation begins now.
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x374ef884), 0x0, 0x3748a000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x374ef8b8), 0x0, 0x3748a000) (unimplemented)
thread 'main' panicked at src/dyld.rs:604:9:
Call to unimplemented function _objc_getClass
```
The error is telling me the app is attempting to call a function that is not implemented/does not exist? Is there a way to reconcile `_objc_getClass` missing here? When I rerun using `RUST_BACKTRACE=full` instead to show the full stacktrace, the error comes out to:

```
...
CPU emulation begins now.
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x374ef884), 0x0, 0x3748a000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x374ef8b8), 0x0, 0x3748a000) (unimplemented)
thread 'main' panicked at src/dyld.rs:604:9:
Call to unimplemented function _objc_getClass
stack backtrace:
   0:        0x10708abb5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha9ed2e5c0690da7d
   1:        0x1070adae3 - core::fmt::write::h861b7654497f40bf
   2:        0x107087dce - std::io::Write::write_fmt::hceb70413cef22e74
   3:        0x10708a989 - std::sys_common::backtrace::print::h48488bc6650dcb03
   4:        0x10708bde5 - std::panicking::default_hook::{{closure}}::h3066cda5ad928fdc
   5:        0x10708bb5e - std::panicking::default_hook::h052c7bf24dcbc1fc
   6:        0x10708c253 - std::panicking::rust_panic_with_hook::hb55ef13d2c0a2cd9
   7:        0x10708c164 - std::panicking::begin_panic_handler::{{closure}}::ha703d9eab3d8cf84
   8:        0x10708b0a9 - std::sys_common::backtrace::__rust_end_short_backtrace::h250d62e205a22ec7
   9:        0x10708bea6 - _rust_begin_unwind
  10:        0x1070ce775 - core::panicking::panic_fmt::h41a5e657af2841f1
  11:        0x106af893b - touchHLE::dyld::Dyld::get_svc_handler::hd312ce3173e8ffa7
  12:        0x106abf58c - touchHLE::environment::Environment::run_inner::hec3a9fd36870ac30
  13:        0x106a3557b - touchHLE::abi::GuestFunction::call::habbbace0e39350e7
  14:        0x106abd0ee - touchHLE::environment::Environment::new::hfbd48055039cbbbc
  15:        0x106a31b54 - touchHLE::main::h32db9d79d82b188f
  16:        0x106a35325 - touchHLE::main::h9bfe2d0a3a83eb5c
  17:        0x106a34f46 - std::sys_common::backtrace::__rust_begin_short_backtrace::hef271c07db81281c
  18:        0x106a34f65 - std::rt::lang_start::{{closure}}::h3e37648a9e84b5f1
  19:        0x107082a50 - std::rt::lang_start_internal::h89215711cfa87541
  20:        0x106a3536c - _main
  21:     0x7ff806590345 - <unknown>
```
Has anyone seen this error and know what it means? I am on macOS 14

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by ciciplusplus** [comment]
The game in question "Cause of Death" is not listed as supported in the appdb https://appdb.touchhle.org/

So this is normal that it's not working.
