### ISSUE TITLE
Constant CFString flags != 0x7C8 (Bike or Die 2 inter alia)

### ISSUE THREAD

**Issue by parkerlreed** [hikari-no-yume/touchHLE#9]
Info.plist

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>CFBundleVersion</key>
        <string>2.1.1</string>
        <key>UIInterfaceOrientation</key>
        <string>UIInterfaceOrientationLandscapeRight</string>
        <key>CFBundleIdentifier</key>
        <string>com.chillingo.bikeordie</string>
        <key>NSMainNibFile</key>
        <string>MainWindow</string>
        <key>CFBundleIconFile</key>
        <string>Icon.png</string>
        <key>CFBundleExecutable</key>
        <string>BikeOrDie</string>
        <key>CFBundleURLTypes</key>
        <array>
                <dict>
                        <key>CFBundleURLName</key>
                        <string>com.toyspring.bikeordie</string>
                        <key>CFBundleURLSchemes</key>
                        <array>
                                <string>bikeordie</string>
                        </array>
                </dict>
        </array>
        <key>DTSDKName</key>
        <string>(SDK_NAME)</string>
        <key>UIStatusBarHidden</key>
        <true/>
        <key>CFBundleDevelopmentRegion</key>
        <string>en</string>
        <key>DTPlatformName</key>
        <string>iphoneos</string>
        <key>CFBundleInfoDictionaryVersion</key>
        <string>6.0</string>
        <key>CFBundleResourceSpecification</key>
        <string>ResourceRules.plist</string>
        <key>CFBundleDisplayName</key>
        <string>Bike or Die!</string>
        <key>CFBundleSignature</key>
        <string>????</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>LSRequiresIPhoneOS</key>
        <true/>
        <key>CFBundleName</key>
        <string>BikeOrDie</string>
</dict>
</plist>
```

touchHLE release backtrace (Unable to build debug currently on Linux). Tested the Windows release in Wine with the same behavior. Window opens for a split second with graphics and crashes.

```
(deck@steamdeck release)$ RUST_BACKTRACE=full ./touchHLE BikeOrDie.app
touchHLE v0.1.0-3-g8f6998e (git) — https://touchhle.org/

Address of start function: GuestFunction(0x2000)
thread 'main' panicked at 'assertion failed: flags == 0x7C8', src/frameworks/foundation/ns_string.rs:586:5
stack backtrace:
   0:     0x5607acb7a16a - std::backtrace_rs::backtrace::libunwind::trace::h34aec3ef6cd8ad7e
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5607acb7a16a - std::backtrace_rs::backtrace::trace_unsynchronized::h8035d38698d0f7a8
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5607acb7a16a - std::sys_common::backtrace::_print_fmt::hff968f6695a1ba22
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5607acb7a16a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7eea0efe77acf1ec
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5607acb9b91e - core::fmt::write::hc553f17407eb0b48
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/fmt/mod.rs:1208:17
   5:     0x5607acb77aa5 - std::io::Write::write_fmt::h62e5f01a089f48c0
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/io/mod.rs:1682:15
   6:     0x5607acb79f35 - std::sys_common::backtrace::_print::h52d116aff3db4cd1
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5607acb79f35 - std::sys_common::backtrace::print::h9e7d2f98fb7af075
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5607acb7b5bf - std::panicking::default_hook::{{closure}}::hf74999dab2d0a95c
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:267:22
   9:     0x5607acb7b2fb - std::panicking::default_hook::hc11ca7d10c44c42f
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:286:9
  10:     0x5607acb7bccc - std::panicking::rust_panic_with_hook::hdb4da1ae79c845a5
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:688:13
  11:     0x5607acb7ba22 - std::panicking::begin_panic_handler::{{closure}}::h02b5b35b126d5cf2
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:577:13
  12:     0x5607acb7a61c - std::sys_common::backtrace::__rust_end_short_backtrace::h6c6853376cf416d1
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x5607acb7b772 - rust_begin_unwind
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
  14:     0x5607ac7333f3 - core::panicking::panic_fmt::hfd9e949092070b66
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
  15:     0x5607ac7334cd - core::panicking::panic::h341545107301821d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:111:5
  16:     0x5607ac7b09fc - touchHLE::frameworks::foundation::ns_string::handle_constant_string::hb8f6014aa7cafb46
  17:     0x5607ac77d7a2 - touchHLE::dyld::Dyld::do_initial_linking::h2d1cb3632a77367b
  18:     0x5607ac7742df - touchHLE::main::h78da24b14fc90263
  19:     0x5607ac7c2cf6 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb06dc5f8a2da40da
  20:     0x5607ac7c9ad2 - std::rt::lang_start::{{closure}}::hacf0aa1800f126f8
  21:     0x5607acb7382c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h9ab31282e87f134a
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:606:13
  22:     0x5607acb7382c - std::panicking::try::do_call::h42ddf5b01d0b4bc7
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
  23:     0x5607acb7382c - std::panicking::try::hfb70320d7386c61a
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
  24:     0x5607acb7382c - std::panic::catch_unwind::h978c9edbad2bb4d4
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
  25:     0x5607acb7382c - std::rt::lang_start_internal::{{closure}}::h04ede5bd2f26b553
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:148:48
  26:     0x5607acb7382c - std::panicking::try::do_call::ha6b9da35a0885c93
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
  27:     0x5607acb7382c - std::panicking::try::h3325520cab3a642e
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
  28:     0x5607acb7382c - std::panic::catch_unwind::h160beec6f047175b
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
  29:     0x5607acb7382c - std::rt::lang_start_internal::h79190e3a877a769d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:148:20
  30:     0x5607ac776975 - main
  31:     0x7f81f6dfd290 - <unknown>
  32:     0x7f81f6dfd34a - __libc_start_main
  33:     0x5607ac748b35 - _start
                               at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
  34:                0x0 - <unknown>
```

**Comment by parkerlreed** [comment]
Managed to catch a brief frame of the window 

![image](https://user-images.githubusercontent.com/841440/216746419-92b75d31-0f4f-4aba-802e-0938c5977779.png)

**Comment by hikari-no-yume** [comment]
I'm guessing the graphics you see are just the Default.png file (a splash screen basically) inside the bundle, because the error this is hitting happens early enough in startup that the app couldn't have actually displayed anything yet.

**Comment by parkerlreed** [comment]
I figured that was probably the case. This was the first thing that came to mind for iOS 2. Very excited to see where this goes!

**Comment by hikari-no-yume** [comment]
Right now basically nothing except Super Monkey Ball is going to work, and there's probably dozens or hundreds of other issues that will prevent this game from starting, but I'll keep this open as a reminder about this first issue (the assertion).

**Comment by TylerJaacks** [comment]
@hikari-no-yume Where did you get your documentation for CFString? Cause I'm looking at this bug cause it is affecting other apps such as Oregon Trail 2009. I'm not sure what the mean of the flag 0x7CB is can according to your comment ur not sure either.

**Comment by hikari-no-yume** [comment]
I couldn't find documentation for it, everything I know about it is guesswork.

**Comment by abnormalmaps** [comment]
Looking at this and another app with the same flag, it seems like flag 0x7D0 indicates UTF16-LE data. I'd be open to making a quick PR for this.

**Comment by TylerJaacks** [comment]
@LennyKappa this is stopping a lot of other applications from running so it would make a big difference

**Comment by TylerJaacks** [comment]
@LennyKappa also where did u find that out from?

**Comment by hikari-no-yume** [comment]
@TylerJaacks It's the _first_ thing stopping a lot of apps from running. There may be hundreds of other issues that would also stop them if they were fixed.

**Comment by TylerJaacks** [comment]
@TylerJaacks i'm aware but you have to fix this to see what fails next

**Comment by hikari-no-yume** [comment]
@LennyKappa Please do, if you want to. :)
